# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='q_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.Question'),
        ),
    ]
